#!/usr/bin/env python3
"""Initialize a project directory with the Harness Workflow structure.

Creates .harness/ state, OpenSpec directory structure, and copies templates.
Delegates to OpenSpec CLI when available.

Usage:
    python run.py init_harness.py . --feature add-auth
    python run.py init_harness.py /path/to/project --force
"""

import argparse
import json
import shlex
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

from harness_shared import (
    detect_build_commands,
    detect_language,
    detect_package_manager,
    detect_framework,
    detect_openspec_cli,
    run_command,
    save_state,
)

SKILL_DIR = SCRIPTS_DIR.parent
TEMPLATES_DIR = SKILL_DIR / "templates"
CONFIG_DIR = SKILL_DIR / "config"
CICD_TEMPLATES_DIR = TEMPLATES_DIR / "cicd"

OPENSPEC_CONFIG_YAML = """\
schema: "1.0"
tools:
  - claude
context:
  description: "Auto-generated by harness-workflow init"
"""


def create_harness_dir(
    project_dir: Path,
    language: str,
    framework: Optional[str],
    package_manager: Optional[str],
    force: bool = False,
) -> Dict[str, Any]:
    """Create .harness/ directory with state.json and config.yaml."""
    harness_dir = project_dir / ".harness"

    if harness_dir.exists() and not force:
        state_file = harness_dir / "state.json"
        if state_file.exists():
            return {"existed": True, "path": str(harness_dir)}

    harness_dir.mkdir(parents=True, exist_ok=True)

    state = {
        "version": "2.0.0",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "language": language,
        "framework": framework,
        "package_manager": package_manager,
        "stages": {
            "intent": "pending",
            "spec": "pending",
            "plan": "pending",
            "harness": "pending",
            "execute": "pending",
        },
        "current_stage": "intent",
    }
    save_state(project_dir, state)

    config_src = CONFIG_DIR / "harness-config.yaml"
    config_dst = harness_dir / "config.yaml"
    if config_src.exists() and (not config_dst.exists() or force):
        shutil.copy2(config_src, config_dst)

    return {"existed": False, "path": str(harness_dir)}


def create_openspec_structure(
    project_dir: Path,
    feature_name: str,
    force: bool = False,
) -> Dict[str, Any]:
    """Create OpenSpec directory structure with per-feature subdirectories.

    Correct structure:
        openspec/
          config.yaml
          changes/
            <feature>/
              .openspec.yaml
              proposal.md
              design.md
              tasks.md
    """
    openspec_dir = project_dir / "openspec"
    changes_dir = openspec_dir / "changes" / feature_name
    created = []

    # Try OpenSpec CLI first
    if detect_openspec_cli():
        print("  OpenSpec CLI detected, delegating initialization...")
        safe_dir = shlex.quote(str(project_dir))
        result = run_command(
            f"openspec init {safe_dir} --tools claude --force",
            project_dir,
            timeout=30,
        )
        if result["success"]:
            print("  Initialized via OpenSpec CLI")
            changes_dir.mkdir(parents=True, exist_ok=True)
            return {"method": "cli", "created": created}
        else:
            print(f"  OpenSpec CLI failed: {result['stderr'].strip()}")
            print("  Falling back to manual structure")

    # Manual structure
    openspec_dir.mkdir(parents=True, exist_ok=True)
    created.append(str(openspec_dir))

    config_path = openspec_dir / "config.yaml"
    if not config_path.exists() or force:
        config_path.write_text(OPENSPEC_CONFIG_YAML, encoding="utf-8")
        created.append(str(config_path))

    changes_dir.mkdir(parents=True, exist_ok=True)
    created.append(str(changes_dir))

    metadata_path = changes_dir / ".openspec.yaml"
    if not metadata_path.exists() or force:
        metadata = {
            "name": feature_name,
            "created": datetime.now(timezone.utc).isoformat(),
            "status": "draft",
            "tools": ["claude"],
        }
        metadata_path.write_text(
            json.dumps(metadata, indent=2) + "\n",
            encoding="utf-8",
        )
        created.append(str(metadata_path))

    template_mapping = {
        "proposal.md": "proposal.md",
        "design.md": "design.md",
        "tasks.md": "tasks.md",
    }
    for template_name, dest_name in template_mapping.items():
        src = TEMPLATES_DIR / template_name
        dst = changes_dir / dest_name
        if src.exists() and (not dst.exists() or force):
            shutil.copy2(src, dst)
            created.append(str(dst))

    return {"method": "manual", "created": created}


def create_intent_file(project_dir: Path, force: bool = False) -> Dict[str, Any]:
    """Copy intent.md template to project root."""
    src = TEMPLATES_DIR / "intent.md"
    dst = project_dir / "intent.md"

    if not src.exists():
        return {"copied": False, "reason": "Template not found"}

    if dst.exists() and not force:
        return {"copied": False, "reason": "Already exists (use --force to overwrite)"}

    shutil.copy2(src, dst)
    return {"copied": True, "path": str(dst)}


def setup_hooks(project_dir: Path, language: str, force: bool = False) -> Dict[str, Any]:
    """Generate language-appropriate lefthook configuration with harness integration."""
    hook_dst = project_dir / "lefthook.yml"

    if hook_dst.exists() and not force:
        return {"copied": False, "reason": "Already exists"}

    # Language-specific hook commands
    lang_configs: Dict[str, Dict[str, Any]] = {
        "typescript": {
            "lint": "npm run lint",
            "format": "npm run format -- --check",
            "typecheck": "npx tsc --noEmit",
            "test": "npm run test:coverage",
            "security": "npm audit --audit-level=moderate",
        },
        "javascript": {
            "lint": "npm run lint",
            "format": "npm run format -- --check",
            "test": "npm run test:coverage",
            "security": "npm audit --audit-level=moderate",
        },
        "python": {
            "lint": "ruff check .",
            "format": "ruff format --check .",
            "typecheck": "mypy .",
            "test": "pytest --cov",
            "security": "pip audit",
        },
        "go": {
            "lint": "golangci-lint run",
            "typecheck": "go vet ./...",
            "test": "go test ./...",
            "security": "govulncheck ./...",
        },
        "rust": {
            "lint": "cargo clippy -- -D warnings",
            "format": "cargo fmt --check",
            "test": "cargo test",
            "security": "cargo audit",
        },
        "java": {
            "lint": "./mvnw spotless:check",
            "typecheck": "./mvnw compile",
            "test": "./mvnw test",
            "security": "./mvnw org.owasp:dependency-check:check",
        },
        "csharp": {
            "lint": "dotnet format --verify-no-changes --no-restore",
            "format": "dotnet format --verify-no-changes --no-restore",
            "typecheck": "dotnet build --no-restore",
            "test": "dotnet test --no-build",
            "security": "dotnet list package --vulnerable",
        },
    }

    config = lang_configs.get(language, {})
    lines = [
        "# Git Hooks Configuration — generated by harness-workflow",
        f"# Language: {language}",
        "",
        "# Pre-commit hooks",
        "pre-commit:",
        "  parallel: true",
        "  commands:",
    ]

    if "lint" in config:
        lines.extend([
            "    lint:",
            f"      run: {config['lint']}",
        ])
    if "format" in config:
        lines.extend([
            "    format:",
            f"      run: {config['format']}",
        ])
    if "typecheck" in config:
        lines.extend([
            "    typecheck:",
            f"      run: {config['typecheck']}",
        ])

    lines.extend([
        "",
        "# Pre-push hooks — includes harness build-verify",
        "pre-push:",
        "  commands:",
        "    harness-verify:",
        "      run: python scripts/run.py build_verify.py --loop tight --max-iterations 3",
        "      env:",
        "        CI: true",
    ])

    if "test" in config:
        lines.extend([
            "    test-coverage:",
            f"      run: {config['test']}",
            "      env:",
            "        CI: true",
        ])
    if "security" in config:
        lines.extend([
            "    security-audit:",
            f"      run: {config['security']}",
        ])

    lines.extend([
        "",
        "# Commit message validation",
        'commit-msg:',
        "  commands:",
        "    conventional:",
        "      run: |",
        "        msg=$(cat {1})",
        '        if ! echo "$msg" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|perf|ci)(\\(.+\\))?: .{1,}$"; then',
        '          echo "Commit message must follow conventional commits format"',
        '          exit 1',
        "        fi",
        "",
    ])

    hook_dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"copied": True, "path": str(hook_dst), "language": language}


def setup_git(project_dir: Path) -> Dict[str, Any]:
    """Initialize git repository with .gitignore and optional lefthook."""
    git_dir = project_dir / ".git"

    if git_dir.exists():
        return {"existed": True, "path": str(git_dir)}

    result = run_command("git init", project_dir, timeout=10)
    if not result["success"]:
        return {"failed": True, "error": result.get("stderr", "git init failed")}

    # Create .gitignore if missing
    gitignore = project_dir / ".gitignore"
    gitignore_created = False
    if not gitignore.exists():
        gitignore.write_text(
            ".harness/\n"
            ".omc/\n"
            "__pycache__/\n"
            "node_modules/\n"
            ".venv/\n"
            "dist/\n"
            "bin/\n"
            "obj/\n"
            "*.pyc\n"
            "*.pyo\n",
            encoding="utf-8",
        )
        gitignore_created = True

    # Try to install lefthook hooks if lefthook.yml exists
    lefthook_installed = False
    lefthook_yml = project_dir / "lefthook.yml"
    if lefthook_yml.exists():
        lh_result = run_command("npx lefthook install", project_dir, timeout=30)
        lefthook_installed = lh_result["success"]

    return {
        "initialized": True,
        "gitignore_created": gitignore_created,
        "lefthook_installed": lefthook_installed,
    }


def setup_claude_hooks(
    project_dir: Path, language: str, force: bool = False
) -> Dict[str, Any]:
    """Generate Claude Code hooks for quality enforcement without git.

    Creates .claude/settings.json with:
    - PostToolUse (Edit|Write): injects lint results after file changes
    - Stop: runs full build-verify before session ends
    """
    claude_dir = project_dir / ".claude"
    settings_path = claude_dir / "settings.json"

    if settings_path.exists() and not force:
        return {"skipped": True, "reason": ".claude/settings.json exists (use --force)"}

    commands = detect_build_commands(project_dir, language)

    post_tool_hooks = []
    stop_hooks = []

    # PostToolUse: lint check after each file edit
    lint_cmd = commands.get("lint")
    if lint_cmd:
        post_tool_hooks.append({
            "matcher": "Edit|Write",
            "hooks": [{
                "type": "command",
                "command": f"{lint_cmd} 2>&1 || echo '[HARNESS] Lint check failed'",
            }],
        })

    # Stop: full verification before session ends
    stop_cmds = []
    for check in ("lint", "typecheck", "test"):
        cmd = commands.get(check)
        if cmd:
            stop_cmds.append(f"({cmd} 2>&1 && echo '[HARNESS] {check} PASSED') || echo '[HARNESS] {check} FAILED'")

    if stop_cmds:
        stop_cmd = " && ".join(stop_cmds)
        stop_hooks.append({
            "hooks": [{
                "type": "command",
                "command": stop_cmd,
            }],
        })

    if not post_tool_hooks and not stop_hooks:
        return {"skipped": True, "reason": f"No build commands detected for {language}"}

    # Merge with existing settings
    existing = {}
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass

    existing.setdefault("hooks", {})
    if post_tool_hooks:
        existing["hooks"]["PostToolUse"] = post_tool_hooks
    if stop_hooks:
        existing["hooks"]["Stop"] = stop_hooks

    claude_dir.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(
        json.dumps(existing, indent=2) + "\n",
        encoding="utf-8",
    )

    return {
        "created": True,
        "path": str(settings_path),
        "hooks_count": len(post_tool_hooks) + len(stop_hooks),
    }


def detect_existing_cicd(project_dir: Path) -> list:
    """Detect existing CI/CD configuration files."""
    existing = []
    candidates = [
        project_dir / ".github" / "workflows",
        project_dir / ".gitlab-ci.yml",
        project_dir / ".circleci",
        project_dir / "Jenkinsfile",
        project_dir / "azure-pipelines.yml",
        project_dir / "lefthook.yml",
    ]
    for path in candidates:
        if path.is_dir() and any(path.iterdir()):
            existing.append(str(path))
        elif path.is_file():
            existing.append(str(path))
    return existing


def detect_project_name(project_dir: Path) -> str:
    """Detect project name from package manifest files."""
    for manifest in ("package.json", "pyproject.toml", "go.mod", "pom.xml", "Cargo.toml"):
        manifest_path = project_dir / manifest
        if manifest_path.exists():
            try:
                content = manifest_path.read_text(encoding="utf-8")
                if manifest == "package.json":
                    import re
                    match = re.search(r'"name"\s*:\s*"([^"]+)"', content)
                    if match:
                        return match.group(1)
                elif manifest == "pyproject.toml":
                    import re
                    match = re.search(r"name\s*=\s*['\"]([^'\"]+)['\"]", content)
                    if match:
                        return match.group(1)
                elif manifest == "go.mod":
                    for line in content.splitlines()[:5]:
                        if line.startswith("module "):
                            return line.split()[-1].split("/")[-1]
            except OSError:
                pass
    return project_dir.name


def detect_language_version(project_dir: Path, language: str) -> str:
    """Detect language version from config files."""
    import re
    version_defaults = {
        "typescript": "20", "javascript": "20",
        "python": "3.12", "go": "1.22",
        "java": "17", "rust": "1.77",
    }
    # Try .node-version, .python-version, go.mod, etc.
    version_files = {
        "typescript": [".node-version", ".nvmrc"],
        "javascript": [".node-version", ".nvmrc"],
        "python": [".python-version", ".tool-versions"],
        "go": ["go.mod"],
        "java": [".java-version"],
    }
    for vf in version_files.get(language, []):
        vp = project_dir / vf
        if vp.exists():
            try:
                content = vp.read_text(encoding="utf-8").strip()
                if vf == "go.mod":
                    match = re.search(r"go\s+(\d+[\.\d]*)", content)
                    if match:
                        return match.group(1)
                else:
                    return content.split()[0]
            except OSError:
                pass
    return version_defaults.get(language, "latest")


def render_template(template_path: Path, context: dict) -> str:
    """Render a template with simple {variable} replacement."""
    try:
        content = template_path.read_text(encoding="utf-8")
    except OSError:
        return ""
    for key, value in context.items():
        content = content.replace(f"{{{key}}}", str(value))
    return content


def generate_cicd(
    project_dir: Path,
    language: str,
    ci_provider: str = "github-actions",
    force: bool = False,
) -> Dict[str, Any]:
    """Generate CI/CD pipeline files based on detected language.

    Creates GitHub Actions workflow, Lefthook config, and PR template
    from language-specific templates in templates/cicd/.
    """
    lang_map = {
        "typescript": "typescript",
        "javascript": "typescript",  # JS uses same template as TS
        "python": "python",
        "go": "go",
        "java": "java",
    }
    template_lang = lang_map.get(language)
    if not template_lang:
        return {"skipped": True, "reason": f"No CI/CD template for language: {language}"}

    # Check existing CI/CD
    existing = detect_existing_cicd(project_dir)
    if existing and not force:
        return {
            "skipped": True,
            "reason": f"Existing CI/CD found: {existing}. Use --force-cicd to overwrite.",
        }

    project_name = detect_project_name(project_dir)
    lang_version = detect_language_version(project_dir, language)

    # Detect install command
    install_commands = {
        "typescript": "npm ci",
        "javascript": "npm ci",
        "python": "pip install -r requirements-dev.txt",
        "go": "",
        "java": "",
    }
    pkg_managers = {
        "typescript": "npm",
        "javascript": "npm",
        "python": "pip",
        "go": "",
        "java": "maven",
    }

    context = {
        "project_name": project_name,
        "language_version": lang_version,
        "install_command": install_commands.get(language, ""),
        "package_manager": pkg_managers.get(language, "npm"),
    }

    generated = []

    # 1. GitHub Actions workflow
    if ci_provider == "github-actions":
        workflow_template = CICD_TEMPLATES_DIR / f"{template_lang}-quality.yml"
        if workflow_template.exists():
            workflow_content = render_template(workflow_template, context)
            workflow_dir = project_dir / ".github" / "workflows"
            workflow_dir.mkdir(parents=True, exist_ok=True)
            workflow_path = workflow_dir / "quality.yml"
            workflow_path.write_text(workflow_content, encoding="utf-8")
            generated.append(str(workflow_path))

    # 2. Lefthook config
    lefthook_map = {
        "typescript": "lefthook-ts.yml",
        "javascript": "lefthook-ts.yml",
        "python": "lefthook-py.yml",
        "go": "lefthook-go.yml",
    }
    lefthook_template_name = lefthook_map.get(language)
    if lefthook_template_name:
        lefthook_template = CICD_TEMPLATES_DIR / lefthook_template_name
        if lefthook_template.exists():
            lefthook_content = render_template(lefthook_template, context)
            lefthook_path = project_dir / "lefthook.yml"
            lefthook_path.write_text(lefthook_content, encoding="utf-8")
            generated.append(str(lefthook_path))

    # 3. PR template
    pr_template = CICD_TEMPLATES_DIR / "pr-template.md"
    if pr_template.exists():
        pr_dir = project_dir / ".github"
        pr_dir.mkdir(parents=True, exist_ok=True)
        pr_path = pr_dir / "pull_request_template.md"
        pr_content = render_template(pr_template, context)
        pr_path.write_text(pr_content, encoding="utf-8")
        generated.append(str(pr_path))

    return {"generated": generated, "language": language, "provider": ci_provider}


def validate_setup(project_dir: Path) -> bool:
    """Verify that initialization completed successfully."""
    checks = [
        project_dir / ".harness" / "state.json",
        project_dir / ".harness" / "config.yaml",
        project_dir / "openspec" / "config.yaml",
    ]

    changes_dir = project_dir / "openspec" / "changes"
    has_changes = (
        changes_dir.is_dir() and any(changes_dir.iterdir())
        if changes_dir.exists()
        else False
    )

    missing = [str(p) for p in checks if not p.exists()]

    if missing:
        print("  Warning: Missing files:")
        for f in missing:
            print(f"    - {f}")

    if not has_changes:
        print("  Warning: No change directories found in openspec/changes/")

    return len(missing) == 0 and has_changes


def main():
    parser = argparse.ArgumentParser(
        description="Initialize a project with Harness Workflow structure",
    )
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Project directory to initialize (default: current)",
    )
    parser.add_argument(
        "--feature",
        default="initial",
        help="Feature name for the change directory (default: initial)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )
    parser.add_argument(
        "--git",
        action="store_true",
        help="Initialize git repository with lefthook hooks",
    )
    parser.add_argument(
        "--claude-hooks",
        action="store_true",
        help="Generate Claude Code hooks for quality enforcement",
    )
    parser.add_argument(
        "--cicd",
        action="store_true",
        default=True,
        help="Generate CI/CD pipeline files (default: true)",
    )
    parser.add_argument(
        "--no-cicd",
        action="store_true",
        help="Skip CI/CD pipeline generation",
    )
    parser.add_argument(
        "--ci-provider",
        choices=["github-actions", "none"],
        default="github-actions",
        help="CI/CD provider (default: github-actions)",
    )
    parser.add_argument(
        "--force-cicd",
        action="store_true",
        help="Overwrite existing CI/CD files",
    )
    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()

    if not project_dir.exists():
        project_dir.mkdir(parents=True)
        print(f"Created directory: {project_dir}")

    print(f"Initializing Harness Workflow in: {project_dir}")
    print(f"Feature: {args.feature}")
    print()

    # Detect project info
    language = detect_language(project_dir)
    if language:
        print(f"  Detected language: {language}")
    else:
        language = "unknown"
        print("  No language detected (generic project)")

    pkg_mgr = detect_package_manager(project_dir, language)
    if pkg_mgr:
        print(f"  Package manager: {pkg_mgr}")

    framework = detect_framework(project_dir, language)
    if framework:
        print(f"  Framework: {framework}")

    print()

    # Step 1: Create .harness/
    print("Creating .harness/ directory...")
    harness_result = create_harness_dir(
        project_dir, language, framework, pkg_mgr, force=args.force
    )
    if harness_result.get("existed"):
        print("  .harness/ already exists (use --force to overwrite)")
    else:
        print(f"  Created: {harness_result['path']}")

    # Step 2: Create OpenSpec structure
    print("Creating OpenSpec structure...")
    openspec_result = create_openspec_structure(
        project_dir, args.feature, force=args.force
    )
    print(f"  Method: {openspec_result['method']}")
    for path in openspec_result.get("created", []):
        print(f"  Created: {path}")

    # Step 3: Copy intent template
    print("Creating intent.md...")
    intent_result = create_intent_file(project_dir, force=args.force)
    if intent_result.get("copied"):
        print(f"  Created: {intent_result['path']}")
    else:
        print(f"  Skipped: {intent_result.get('reason', 'unknown')}")

    # Step 4: Setup hooks
    print("Setting up hooks...")
    hook_result = setup_hooks(project_dir, language, force=args.force)
    if hook_result.get("copied"):
        print(f"  Created: {hook_result['path']}")
    else:
        print(f"  Skipped: {hook_result.get('reason', 'unknown')}")

    # Step 5: Git init (if --git)
    if args.git:
        print("Initializing git repository...")
        git_result = setup_git(project_dir)
        if git_result.get("existed"):
            print("  Git already initialized")
        elif git_result.get("initialized"):
            print("  Git repository initialized")
            if git_result.get("gitignore_created"):
                print("  Created .gitignore")
            if git_result.get("lefthook_installed"):
                print("  Lefthook hooks installed")
            else:
                print("  Note: Lefthook not found. Install with: npm install -D lefthook")
        elif git_result.get("failed"):
            print(f"  Failed: {git_result.get('error', 'unknown')}")
    else:
        print("Git: skipped (use --git to initialize)")

    # Step 6: Claude Code hooks (if --claude-hooks)
    if args.claude_hooks:
        print("Setting up Claude Code hooks...")
        cc_result = setup_claude_hooks(project_dir, language, force=args.force)
        if cc_result.get("created"):
            print(f"  Created: {cc_result['path']}")
            print(f"  Hooks configured: {cc_result['hooks_count']}")
        elif cc_result.get("skipped"):
            print(f"  Skipped: {cc_result['reason']}")
    else:
        print("Claude Code hooks: skipped (use --claude-hooks to enable)")

    # Step 7: CI/CD generation
    do_cicd = args.cicd and not getattr(args, "no_cicd", False)
    if do_cicd:
        print("Generating CI/CD pipeline files...")
        cicd_result = generate_cicd(
            project_dir,
            language,
            ci_provider=args.ci_provider,
            force=args.force_cicd,
        )
        if cicd_result.get("skipped"):
            print(f"  Skipped: {cicd_result['reason']}")
        else:
            for path in cicd_result.get("generated", []):
                print(f"  Created: {path}")
            if not cicd_result.get("generated"):
                print("  No templates matched for this language")
    else:
        print("CI/CD: skipped (use --cicd to generate)")

    # Step 8: Validate
    print()
    if validate_setup(project_dir):
        print("Initialization complete!")
    else:
        print("Initialization completed with warnings.")
        print("Run `python scripts/run.py check_status.py` to see details.")

    print()
    print("Next steps:")
    print("  1. Edit intent.md to describe your project goals")
    if not args.git:
        print("  2. (Recommended) Re-run with --git for hard quality enforcement via git hooks")
    if not args.claude_hooks:
        print("  3. (Recommended) Re-run with --claude-hooks for Claude Code session hooks")
    print("  4. Run: python scripts/run.py check_status.py")


if __name__ == "__main__":
    main()
